name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check codestyle
      run: |
        git ls-files *.{c,h} | xargs clang-format -i --verbose
        git diff --exit-code

    - name: Build application
      run: make
        
    - name: Build tests
      run: make source
      
    - name: Run tests
      run: make run_source
